"""empty message

Revision ID: 34e61dcb1967
Revises: ff9811be878c
Create Date: 2021-06-18 18:23:20.109071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e61dcb1967'
down_revision = 'ff9811be878c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('looking_for_talent', sa.Boolean(), nullable=True))
    op.drop_column('Venue', 'looking_for_venues')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('looking_for_venues', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'looking_for_talent')
    # ### end Alembic commands ###
