"""empty message

Revision ID: 752077348130
Revises: c3fe2818d9a3
Create Date: 2021-06-24 16:10:41.167079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752077348130'
down_revision = 'c3fe2818d9a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'genres')
    # ### end Alembic commands ###
