"""empty message

Revision ID: d856cc3bd674
Revises: db368a0450f4
Create Date: 2021-06-21 15:32:05.743081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd856cc3bd674'
down_revision = 'db368a0450f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    op.add_column('genres', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'genres', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genres', type_='foreignkey')
    op.drop_column('genres', 'venue_id')
    op.add_column('Venue', sa.Column('genres', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
